"""Initial migration

Revision ID: 2a49c6bbac12
Revises: 
Create Date: 2024-11-28 10:12:57.615155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a49c6bbac12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=False),
    sa.Column('primary_language', sa.String(length=20), nullable=False),
    sa.Column('other_languages', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('course', sa.String(length=20), nullable=False),
    sa.Column('profile_picture', sa.String(length=250), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=15), nullable=True),
    sa.Column('instagram_handle', sa.String(length=50), nullable=True),
    sa.Column('linkedin_handle', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('instagram_handle'),
    sa.UniqueConstraint('linkedin_handle'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('whatsapp_number')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('user')
    # ### end Alembic commands ###
